
    import './styles.scoped.css';
    export default {
  "content-enter": "awsui_content-enter_gwq0h_wn6xw_157",
  "awsui-motion-fade-in": "awsui_awsui-motion-fade-in_gwq0h_wn6xw_1",
  "trigger-expanded": "awsui_trigger-expanded_gwq0h_wn6xw_179",
  "icon": "awsui_icon_gwq0h_wn6xw_193",
  "root": "awsui_root_gwq0h_wn6xw_207",
  "expand-button": "awsui_expand-button_gwq0h_wn6xw_245",
  "expanded": "awsui_expanded_gwq0h_wn6xw_253",
  "icon-container": "awsui_icon-container_gwq0h_wn6xw_263",
  "icon-container-container": "awsui_icon-container-container_gwq0h_wn6xw_267",
  "wrapper": "awsui_wrapper_gwq0h_wn6xw_271",
  "wrapper-default": "awsui_wrapper-default_gwq0h_wn6xw_279",
  "wrapper-inline": "awsui_wrapper-inline_gwq0h_wn6xw_279",
  "wrapper-footer": "awsui_wrapper-footer_gwq0h_wn6xw_279",
  "wrapper-navigation": "awsui_wrapper-navigation_gwq0h_wn6xw_283",
  "wrapper-container": "awsui_wrapper-container_gwq0h_wn6xw_286",
  "wrapper-compact": "awsui_wrapper-compact_gwq0h_wn6xw_290",
  "header-deprecated": "awsui_header-deprecated_gwq0h_wn6xw_303",
  "wrapper-expanded": "awsui_wrapper-expanded_gwq0h_wn6xw_309",
  "header": "awsui_header_gwq0h_wn6xw_303",
  "header-wrapper": "awsui_header-wrapper_gwq0h_wn6xw_346",
  "header-actions-wrapper": "awsui_header-actions-wrapper_gwq0h_wn6xw_358",
  "header-button": "awsui_header-button_gwq0h_wn6xw_364",
  "header-container-button": "awsui_header-container-button_gwq0h_wn6xw_364",
  "header-container": "awsui_header-container_gwq0h_wn6xw_364",
  "header-navigation": "awsui_header-navigation_gwq0h_wn6xw_399",
  "header-text": "awsui_header-text_gwq0h_wn6xw_436",
  "content": "awsui_content_gwq0h_wn6xw_157",
  "content-default": "awsui_content-default_gwq0h_wn6xw_449",
  "content-inline": "awsui_content-inline_gwq0h_wn6xw_449",
  "content-footer": "awsui_content-footer_gwq0h_wn6xw_453",
  "content-expanded": "awsui_content-expanded_gwq0h_wn6xw_457",
  "content-compact": "awsui_content-compact_gwq0h_wn6xw_460",
  "focusable": "awsui_focusable_gwq0h_wn6xw_464",
  "click-target": "awsui_click-target_gwq0h_wn6xw_479"
};
  